import React, { useState, useMemo } from "react";
import {
  Dialog,
  Flex,
  Box,
  Button,
  Tabs,
  Text,
  ScrollArea,
  Switch,
} from "@radix-ui/themes";
import {
  Cross2Icon,
  CopyIcon,
  CheckIcon,
  DownloadIcon,
  OpenInNewWindowIcon,
} from "@radix-ui/react-icons";
import { useAppStore } from "../store/useAppStore";
import { generateColor } from "../utils/colorEngine";
import { converter } from "culori";

const toOklch = converter("oklch");

type ExportFormat =
  | "css"
  | "scss"
  | "tailwind"
  | "json"
  | "markdown"
  | "tokens"
  | "svg"
  | "html"
  | "csv"
  | "swiftui"
  | "figma";

interface ProjectExportDialogProps {
  isOpen: boolean;
  onClose: () => void;
}

/**
 * Project-wide Export Dialog
 * Exports all scales from the active project at once
 */
export const ProjectExportDialog: React.FC<ProjectExportDialogProps> = ({
  isOpen,
  onClose,
}) => {
  const { getCurrentProject, getLightnessSteps } = useAppStore();
  const project = getCurrentProject();

  const [activeFormat, setActiveFormat] = useState<ExportFormat>("css");
  const [includeMetadata, setIncludeMetadata] = useState(true);
  const [includeP3, setIncludeP3] = useState(true);
  const [copied, setCopied] = useState(false);

  // Generate all colors for all scales
  const allScaleData = useMemo(() => {
    if (!project) return [];

    return project.scales.map((scale) => {
      const lightnessSteps = getLightnessSteps(scale);
      const colors = lightnessSteps.map((lightnessStep) => {
        const lNormalized = lightnessStep / 100;
        return generateColor(
          lNormalized,
          scale.manualChroma,
          scale.hue,
          scale.hueCurve,
          scale.chromaCurve,
          {
            contrastMode: scale.contrastMode || "standard",
            calculateContrast: true,
            targetBackground: scale.targetBackground || "black",
            targetLc: scale.apcaTargetLc,
            targetWcagRatio: scale.wcagTargetRatio,
            chromaCompensation: scale.chromaCompensation ?? true,
          }
        );
      });

      return {
        scale,
        colors,
        lightnessSteps,
      };
    });
  }, [project, getLightnessSteps]);

  const generateProjectCSS = () => {
    let css = includeMetadata
      ? `/* ${project?.name || "Project"} - Generated by Lumat\n` +
        ` * ${project?.scales.length} color scales\n` +
        ` * Generated: ${new Date().toLocaleDateString()}\n */\n\n`
      : "";

    css += ":root {\n";

    allScaleData.forEach(({ scale, colors, lightnessSteps }) => {
      const scaleName = scale.name.toLowerCase().replace(/\s+/g, "-");

      if (includeMetadata) {
        css += `\n  /* ${scale.name} - Hue: ${scale.hue}° | Chroma: ${(
          scale.manualChroma || 0
        ).toFixed(2)} */\n`;
      }

      colors.forEach((color, index) => {
        const step = lightnessSteps[index];
        css += `  --${scaleName}-${step}: ${color.hex};\n`;
        if (includeP3) {
          css += `  --${scaleName}-${step}-p3: ${color.cssP3};\n`;
        }
      });
    });

    css += "}\n";
    return css;
  };

  const generateProjectSCSS = () => {
    let scss = includeMetadata
      ? `// ${project?.name || "Project"} - Generated by Lumat\n` +
        `// ${project?.scales.length} color scales\n` +
        `// Generated: ${new Date().toLocaleDateString()}\n\n`
      : "";

    allScaleData.forEach(({ scale, colors, lightnessSteps }) => {
      const scaleName = scale.name.toLowerCase().replace(/\s+/g, "-");

      if (includeMetadata) {
        scss += `// ${scale.name}\n`;
      }

      colors.forEach((color, index) => {
        const step = lightnessSteps[index];
        scss += `$${scaleName}-${step}: ${color.hex};\n`;
        if (includeP3) {
          scss += `$${scaleName}-${step}-p3: ${color.cssP3};\n`;
        }
      });
      scss += "\n";
    });

    return scss;
  };

  const generateProjectTailwind = () => {
    let config = includeMetadata
      ? `// ${project?.name || "Project"} - Generated by Lumat\n` +
        `// Add to tailwind.config.js\n\n`
      : "";

    config += `module.exports = {\n`;
    config += `  theme: {\n`;
    config += `    extend: {\n`;
    config += `      colors: {\n`;

    allScaleData.forEach(({ scale, colors, lightnessSteps }) => {
      const scaleName = scale.name.toLowerCase().replace(/\s+/g, "-");
      config += `        ${scaleName}: {\n`;

      colors.forEach((color, index) => {
        const step = lightnessSteps[index];
        config += `          ${step}: '${color.hex}',\n`;
      });

      config += `        },\n`;
    });

    config += `      },\n`;
    config += `    },\n`;
    config += `  },\n`;
    config += `}\n`;

    return config;
  };

  const generateProjectJSON = () => {
    const data = {
      name: project?.name || "Project",
      ...(includeMetadata && {
        metadata: {
          scalesCount: project?.scales.length || 0,
          generatedAt: new Date().toISOString(),
        },
      }),
      scales: allScaleData.reduce<Record<string, Record<string, unknown>>>(
        (acc, { scale, colors, lightnessSteps }) => {
          const scaleName = scale.name.toLowerCase().replace(/\s+/g, "-");
          acc[scaleName] = {
            ...(includeMetadata && {
              metadata: {
                hue: scale.hue,
                chroma: scale.manualChroma,
                contrastMode: scale.contrastMode,
                targetBackground: scale.targetBackground,
              },
            }),
            colors: colors.reduce<Record<string, Record<string, unknown>>>(
              (colorAcc, color, index) => {
                const step = lightnessSteps[index];
                colorAcc[step.toString()] = {
                  hex: color.hex,
                  oklch: color.oklch,
                  ...(includeP3 && { p3: color.cssP3 }),
                  lightness: Math.round(color.L * 100),
                  chroma: parseFloat(color.C.toFixed(4)),
                  hue: parseFloat(color.H.toFixed(1)),
                };
                return colorAcc;
              },
              {}
            ),
          };
          return acc;
        },
        {}
      ),
    };

    return JSON.stringify(data, null, 2);
  };

  const generateProjectTokens = () => {
    return JSON.stringify(
      allScaleData.reduce<Record<string, Record<string, unknown>>>(
        (acc, { scale, colors, lightnessSteps }) => {
          const scaleName = scale.name.toLowerCase().replace(/\s+/g, "-");
          acc[scaleName] = colors.reduce<
            Record<string, Record<string, unknown>>
          >((colorAcc, color, index) => {
            const step = lightnessSteps[index];
            colorAcc[step.toString()] = {
              $type: "color",
              $value: color.hex,
              $description: `${scale.name} ${step}`,
              ...(includeP3 && color.cssP3 && { $p3: color.cssP3 }),
            };
            return colorAcc;
          }, {});
          return acc;
        },
        {}
      ),
      null,
      2
    );
  };

  const generateProjectSwiftUI = () => {
    let swift = includeMetadata
      ? `// ${project?.name || "Project"} - Generated by Lumat\n` +
        `// ${project?.scales.length} color scales\n\n`
      : "";

    swift += `import SwiftUI\n\nextension Color {\n`;

    allScaleData.forEach(({ scale, colors, lightnessSteps }) => {
      const scaleName = scale.name.replace(/\s+/g, "");
      if (includeMetadata) {
        swift += `\n  // ${scale.name}\n`;
      }

      colors.forEach((color, index) => {
        const step = lightnessSteps[index];
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const rgb = toOklch(color.hex as any);
        if (!rgb) return;

        const rgbTyped = rgb as { r?: number; g?: number; b?: number };
        const r = rgbTyped.r || 0;
        const g = rgbTyped.g || 0;
        const b = rgbTyped.b || 0;

        swift += `  static let ${scaleName.toLowerCase()}${step} = Color(red: ${r.toFixed(
          3
        )}, green: ${g.toFixed(3)}, blue: ${b.toFixed(3)})\n`;
      });
    });

    swift += `}\n`;
    return swift;
  };

  const generateProjectFigmaTokens = () => {
    return JSON.stringify(
      allScaleData.reduce<Record<string, Record<string, unknown>>>(
        (acc, { scale, colors, lightnessSteps }) => {
          const scaleName = scale.name.toLowerCase().replace(/\s+/g, "-");
          acc[scaleName] = {
            ...(includeMetadata && {
              $description: `${scale.name} color scale`,
              $metadata: {
                hue: scale.hue,
                chroma: scale.manualChroma,
                contrastMode: scale.contrastMode,
              },
            }),
            ...Object.fromEntries(
              colors.map((color, index) => {
                const step = lightnessSteps[index];
                return [
                  step.toString(),
                  {
                    $value: color.hex,
                    $type: "color",
                    ...(includeP3 && color.cssP3 && { $p3: color.cssP3 }),
                  },
                ];
              })
            ),
          };
          return acc;
        },
        {}
      ),
      null,
      2
    );
  };

  const generateProjectCSV = () => {
    const headers = [
      "Scale",
      "Step",
      "Lightness",
      "Hex",
      "OKLCH",
      "P3",
      "Chroma",
      "Hue",
    ].join(",");

    const rows = allScaleData.flatMap(({ scale, colors, lightnessSteps }) =>
      colors.map((color, index) => {
        const step = lightnessSteps[index];
        return [
          scale.name,
          step,
          Math.round(color.L * 100),
          color.hex,
          color.oklch,
          color.cssP3,
          color.C.toFixed(4),
          color.H.toFixed(1),
        ].join(",");
      })
    );

    return [headers, ...rows].join("\n");
  };

  const generateProjectMarkdown = () => {
    let md = `# ${project?.name || "Project"}\n\n`;

    if (includeMetadata) {
      md += `**Generated:** ${new Date().toLocaleDateString()}\n`;
      md += `**Scales:** ${project?.scales.length || 0}\n\n`;
      md += "---\n\n";
    }

    allScaleData.forEach(({ scale, colors, lightnessSteps }) => {
      md += `## ${scale.name}\n\n`;

      if (includeMetadata) {
        md += `- **Hue:** ${scale.hue}°\n`;
        md += `- **Chroma:** ${(scale.manualChroma || 0).toFixed(2)}\n`;
        md += `- **Contrast Mode:** ${scale.contrastMode}\n`;
        md += `- **Target Background:** ${scale.targetBackground}\n\n`;
      }

      md += `| Step | Lightness | Hex | OKLCH |\n`;
      md += `|------|-----------|-----|-------|\n`;

      colors.forEach((color, index) => {
        const step = lightnessSteps[index];
        md += `| ${step} | ${Math.round(color.L * 100)} | ${color.hex} | ${
          color.oklch
        } |\n`;
      });

      md += "\n";
    });

    md += `---\n*Generated with Lumat on ${new Date().toLocaleDateString()}*\n`;

    return md;
  };

  const generateProjectHTML = () => {
    let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${project?.name || "Project"} - Color Scales</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      background: #09090b;
      color: #fafafa;
      padding: 40px 20px;
    }
    .container { max-width: 1200px; margin: 0 auto; }
    h1 { font-size: 32px; margin-bottom: 8px; }
    .subtitle { color: #a1a1aa; margin-bottom: 40px; }
    .scale-section { margin-bottom: 48px; }
    .scale-title {
      font-size: 24px;
      margin-bottom: 16px;
      padding-bottom: 8px;
      border-bottom: 2px solid #3f3f46;
    }
    .scale-meta {
      color: #a1a1aa;
      font-size: 14px;
      margin-bottom: 20px;
    }
    .swatches {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(140px, 1fr));
      gap: 16px;
    }
    .swatch {
      aspect-ratio: 1;
      border-radius: 8px;
      display: flex;
      flex-direction: column;
      justify-content: flex-end;
      padding: 12px;
      border: 1px solid rgba(255, 255, 255, 0.1);
    }
    .swatch-label {
      font-weight: 600;
      font-size: 14px;
      margin-bottom: 4px;
    }
    .swatch-value {
      font-family: monospace;
      font-size: 11px;
      opacity: 0.8;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>${project?.name || "Project"}</h1>
    <div class="subtitle">
      ${
        project?.scales.length || 0
      } color scales • Generated ${new Date().toLocaleDateString()}
    </div>
`;

    allScaleData.forEach(({ scale, colors, lightnessSteps }) => {
      html += `    <div class="scale-section">
      <h2 class="scale-title">${scale.name}</h2>`;

      if (includeMetadata) {
        html += `
      <div class="scale-meta">
        Hue: ${scale.hue}° | Chroma: ${(scale.manualChroma || 0).toFixed(
          2
        )} | Mode: ${scale.contrastMode}
      </div>`;
      }

      html += `
      <div class="swatches">`;

      colors.forEach((color, index) => {
        const step = lightnessSteps[index];
        const textColor = color.L > 0.5 ? "#000000" : "#ffffff";

        html += `
        <div class="swatch" style="background-color: ${color.hex}; color: ${textColor};">
          <div class="swatch-label">${step}</div>
          <div class="swatch-value">${color.hex}</div>
        </div>`;
      });

      html += `
      </div>
    </div>
`;
    });

    html += `  </div>
</body>
</html>`;

    return html;
  };

  const generateProjectSVG = () => {
    const cellSize = 60;
    const padding = 40;
    const labelWidth = 120;
    const titleHeight = 80;
    const scaleGap = 20;

    const maxSteps = Math.max(
      ...allScaleData.map((d) => d.lightnessSteps.length)
    );
    const totalWidth = padding * 2 + labelWidth + maxSteps * cellSize;
    const scaleHeight = cellSize + scaleGap;
    const totalHeight =
      titleHeight + allScaleData.length * scaleHeight + padding;

    let svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${totalWidth} ${totalHeight}">
  <rect width="${totalWidth}" height="${totalHeight}" fill="#09090b"/>
  <text x="${padding}" y="40" font-size="24" font-weight="600" fill="#fafafa" font-family="system-ui, sans-serif">${
      project?.name || "Project"
    }</text>
  <text x="${padding}" y="65" font-size="14" fill="#a1a1aa" font-family="system-ui, sans-serif">${
      project?.scales.length || 0
    } color scales</text>
`;

    allScaleData.forEach(({ scale, colors, lightnessSteps }, scaleIndex) => {
      const yOffset = titleHeight + scaleIndex * scaleHeight;

      // Scale label
      svg += `  <text x="${padding}" y="${
        yOffset + cellSize / 2 + 5
      }" font-size="14" font-weight="500" fill="#fafafa" font-family="system-ui, sans-serif">${
        scale.name
      }</text>\n`;

      // Color swatches
      colors.forEach((color, index) => {
        const step = lightnessSteps[index];
        const xOffset = padding + labelWidth + index * cellSize;

        svg += `  <rect x="${xOffset}" y="${yOffset}" width="${cellSize}" height="${cellSize}" fill="${
          color.hex
        }" stroke="#3f3f46" stroke-width="1"/>
  <text x="${xOffset + cellSize / 2}" y="${
          yOffset + cellSize / 2 + 5
        }" font-size="11" fill="${
          color.L > 0.5 ? "#000" : "#fff"
        }" text-anchor="middle" font-family="monospace">${step}</text>\n`;
      });
    });

    svg += `</svg>`;
    return svg;
  };

  const getExportContent = () => {
    switch (activeFormat) {
      case "css":
        return generateProjectCSS();
      case "scss":
        return generateProjectSCSS();
      case "tailwind":
        return generateProjectTailwind();
      case "json":
        return generateProjectJSON();
      case "markdown":
        return generateProjectMarkdown();
      case "tokens":
        return generateProjectTokens();
      case "svg":
        return generateProjectSVG();
      case "html":
        return generateProjectHTML();
      case "csv":
        return generateProjectCSV();
      case "swiftui":
        return generateProjectSwiftUI();
      case "figma":
        return generateProjectFigmaTokens();
      default:
        return "";
    }
  };

  const handleCopy = async () => {
    const content = getExportContent();
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const extensions: Record<ExportFormat, string> = {
      css: "css",
      scss: "scss",
      tailwind: "js",
      json: "json",
      markdown: "md",
      tokens: "json",
      svg: "svg",
      html: "html",
      csv: "csv",
      swiftui: "swift",
      figma: "json",
    };

    const mimeTypes: Record<ExportFormat, string> = {
      css: "text/css",
      scss: "text/css",
      tailwind: "application/javascript",
      json: "application/json",
      markdown: "text/markdown",
      tokens: "application/json",
      svg: "image/svg+xml",
      html: "text/html",
      csv: "text/csv",
      swiftui: "text/plain",
      figma: "application/json",
    };

    const content = getExportContent();
    const blob = new Blob([content], { type: mimeTypes[activeFormat] });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${(project?.name || "project")
      .toLowerCase()
      .replace(/\s+/g, "-")}.${extensions[activeFormat]}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleOpenInNewTab = () => {
    if (activeFormat === "html" || activeFormat === "svg") {
      const content = getExportContent();
      const blob = new Blob([content], {
        type: activeFormat === "html" ? "text/html" : "image/svg+xml",
      });
      const url = URL.createObjectURL(blob);
      window.open(url, "_blank");
      setTimeout(() => URL.revokeObjectURL(url), 100);
    }
  };

  const renderPreview = () => {
    if (activeFormat === "html" || activeFormat === "svg") {
      return (
        <Box
          style={{
            width: "100%",
            height: "100%",
            overflow: "auto",
          }}
        >
          <div
            dangerouslySetInnerHTML={{
              __html: getExportContent(),
            }}
          />
        </Box>
      );
    }

    // Code preview
    return (
      <Box p="3">
        <pre
          style={{
            fontFamily: "monospace",
            fontSize: "12px",
            lineHeight: "1.5",
            color: "#fafafa",
            margin: 0,
            whiteSpace: "pre-wrap",
            wordBreak: "break-word",
          }}
        >
          {getExportContent()}
        </pre>
      </Box>
    );
  };

  if (!project) return null;

  return (
    <Dialog.Root open={isOpen} onOpenChange={onClose}>
      <Dialog.Content style={{ maxWidth: "900px", maxHeight: "90vh" }}>
        <Dialog.Title>Export Project: {project.name}</Dialog.Title>
        <Dialog.Description size="2" mb="4">
          Export all {project.scales.length} color scales from this project at
          once
        </Dialog.Description>

        {/* Format Selection */}
        <Box mb="4">
          <Text size="2" weight="bold" mb="2">
            Export Format
          </Text>
          <Tabs.Root
            value={activeFormat}
            onValueChange={(v) => setActiveFormat(v as ExportFormat)}
          >
            <Tabs.List>
              <Tabs.Trigger value="css">CSS</Tabs.Trigger>
              <Tabs.Trigger value="scss">SCSS</Tabs.Trigger>
              <Tabs.Trigger value="tailwind">Tailwind</Tabs.Trigger>
              <Tabs.Trigger value="json">JSON</Tabs.Trigger>
              <Tabs.Trigger value="tokens">Tokens</Tabs.Trigger>
              <Tabs.Trigger value="html">HTML</Tabs.Trigger>
              <Tabs.Trigger value="svg">SVG</Tabs.Trigger>
              <Tabs.Trigger value="markdown">Markdown</Tabs.Trigger>
              <Tabs.Trigger value="csv">CSV</Tabs.Trigger>
              <Tabs.Trigger value="swiftui">SwiftUI</Tabs.Trigger>
              <Tabs.Trigger value="figma">Figma</Tabs.Trigger>
            </Tabs.List>
          </Tabs.Root>
        </Box>

        {/* Options */}
        <Flex gap="4" mb="4" wrap="wrap">
          <Flex align="center" gap="2">
            <Switch
              checked={includeMetadata}
              onCheckedChange={setIncludeMetadata}
            />
            <Text size="2">Include metadata</Text>
          </Flex>
          <Flex align="center" gap="2">
            <Switch checked={includeP3} onCheckedChange={setIncludeP3} />
            <Text size="2">Include P3 colors</Text>
          </Flex>
        </Flex>

        {/* Preview */}
        <Box
          style={{
            backgroundColor: "#09090b",
            border: "1px solid #3f3f46",
            borderRadius: "8px",
            overflow: "hidden",
            marginBottom: "16px",
          }}
        >
          <ScrollArea style={{ height: "400px" }}>{renderPreview()}</ScrollArea>
        </Box>

        {/* Actions */}
        <Flex gap="3" justify="end">
          <Button variant="soft" color="gray" onClick={onClose}>
            Close
          </Button>
          {(activeFormat === "html" || activeFormat === "svg") && (
            <Button variant="soft" onClick={handleOpenInNewTab}>
              <OpenInNewWindowIcon /> Open in New Tab
            </Button>
          )}
          <Button variant="soft" onClick={handleDownload}>
            <DownloadIcon /> Download
          </Button>
          <Button onClick={handleCopy}>
            {copied ? (
              <>
                <CheckIcon /> Copied!
              </>
            ) : (
              <>
                <CopyIcon /> Copy
              </>
            )}
          </Button>
        </Flex>

        <Dialog.Close>
          <button
            style={{
              position: "absolute",
              top: "16px",
              right: "16px",
              background: "none",
              border: "none",
              cursor: "pointer",
              padding: "4px",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              color: "#a1a1aa",
            }}
            aria-label="Close"
          >
            <Cross2Icon width="20" height="20" />
          </button>
        </Dialog.Close>
      </Dialog.Content>
    </Dialog.Root>
  );
};
