/**
 * CSS Export Utilities
 *
 * Enhanced CSS generation with P3/sRGB fallbacks and progressive enhancement
 */

import { ColorResult } from './colorEngine';
import { ColorScale } from '../types';

export interface CSSExportOptions {
  includeP3Fallbacks?: boolean;
  includeComments?: boolean;
  includeLightnessNotes?: boolean;
  format?: 'custom-properties' | 'scss' | 'less';
  rootSelector?: string;
}

/**
 * Generate CSS custom properties with P3/sRGB fallbacks
 * Implements progressive enhancement: sRGB base + P3 override for wide-gamut displays
 */
export function generateCSSWithFallbacks(
  scale: ColorScale,
  colors: ColorResult[],
  lightnessSteps: number[],
  options: CSSExportOptions = {}
): string {
  const {
    includeP3Fallbacks = true,
    includeComments = true,
    includeLightnessNotes = true,
    format = 'custom-properties',
    rootSelector = ':root'
  } = options;

  const scaleName = scale.name.toLowerCase().replace(/\s/g, '-');
  let css = '';

  // Header comment
  if (includeComments) {
    css += `/*\n`;
    css += ` * ${scale.name} Color Scale\n`;
    css += ` * Generated by Lumat Color System Designer\n`;
    css += ` * \n`;
    css += ` * Format: OKLCH (perceptually uniform)\n`;
    css += ` * Gamut: Display P3 (sRGB fallback included)\n`;
    css += ` * Contrast Mode: ${scale.contrastMode || 'standard'}\n`;
    css += ` */\n\n`;
  }

  // sRGB base values (99% browser support)
  css += `${rootSelector} {\n`;
  if (includeComments) {
    css += `  /* sRGB Fallback (hex) - Universal support */\n`;
  }

  colors.forEach((c, i) => {
    const step = lightnessSteps[i];
    const actualL = Math.round(c.L * 100);

    let comment = '';
    if (includeComments) {
      comment += ` /* ${c.oklch}`;
      if (includeLightnessNotes && actualL !== step) {
        comment += ` | Actual L: ${actualL}`;
      }
      comment += ' */';
    }

    css += `  --${scaleName}-${step}: ${c.hex};${comment}\n`;
  });

  // P3 values (if requested)
  if (includeP3Fallbacks) {
    css += `\n`;
    if (includeComments) {
      css += `  /* Display P3 Enhanced Values */\n`;
    }

    colors.forEach((c, i) => {
      const step = lightnessSteps[i];
      let comment = '';
      if (includeComments) {
        comment = ` /* P3 gamut, wider color range */`;
      }

      css += `  --${scaleName}-${step}-p3: ${c.cssP3};${comment}\n`;
    });
  }

  css += `}\n`;

  // Progressive enhancement: P3 override for capable displays
  if (includeP3Fallbacks) {
    css += `\n`;
    if (includeComments) {
      css += `/*\n`;
      css += ` * Progressive Enhancement: P3 Override\n`;
      css += ` * Activates on wide-gamut displays (Safari, Chrome)\n`;
      css += ` */\n`;
    }

    css += `@supports (color: color(display-p3 1 1 1)) {\n`;
    css += `  @media (color-gamut: p3) {\n`;
    css += `    ${rootSelector} {\n`;

    colors.forEach((c, i) => {
      const step = lightnessSteps[i];
      css += `      --${scaleName}-${step}: var(--${scaleName}-${step}-p3);\n`;
    });

    css += `    }\n`;
    css += `  }\n`;
    css += `}\n`;
  }

  // Usage examples
  if (includeComments) {
    css += `\n`;
    css += `/*\n`;
    css += ` * Usage Examples:\n`;
    css += ` * \n`;
    css += ` * .button {\n`;
    css += ` *   background: var(--${scaleName}-${lightnessSteps[Math.floor(lightnessSteps.length / 2)]});\n`;
    css += ` *   color: var(--${scaleName}-${lightnessSteps[0]});\n`;
    css += ` * }\n`;
    css += ` * \n`;
    css += ` * Browser Support:\n`;
    css += ` * - sRGB (hex): 99%+ (all browsers)\n`;
    css += ` * - Display P3: Safari 10+, Chrome 111+, Edge 111+\n`;
    css += ` * - Fallback: Automatic via @supports + @media\n`;
    css += ` */\n`;
  }

  return css;
}

/**
 * Generate Tailwind config for color scale
 */
export function generateTailwindConfig(
  scale: ColorScale,
  colors: ColorResult[],
  lightnessSteps: number[]
): string {
  const scaleName = scale.name.toLowerCase().replace(/\s/g, '-');

  const colorObject: Record<string, string> = {};
  colors.forEach((c, i) => {
    const step = lightnessSteps[i];
    colorObject[step.toString()] = c.hex;
  });

  return `// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      colors: {
        '${scaleName}': ${JSON.stringify(colorObject, null, 8)}
      }
    }
  }
}

// Usage:
// <div className="bg-${scaleName}-98 text-${scaleName}-14">
//   Hello World
// </div>`;
}

/**
 * Generate SCSS variables
 */
export function generateSCSS(
  scale: ColorScale,
  colors: ColorResult[],
  lightnessSteps: number[]
): string {
  const scaleName = scale.name.toLowerCase().replace(/\s/g, '-');
  let scss = '';

  scss += `// ${scale.name} Color Scale\n`;
  scss += `// Generated by Lumat\n\n`;

  colors.forEach((c, i) => {
    const step = lightnessSteps[i];
    const actualL = Math.round(c.L * 100);

    scss += `$${scaleName}-${step}: ${c.hex};`;
    if (actualL !== step) {
      scss += ` // Actual L: ${actualL}`;
    }
    scss += `\n`;
  });

  scss += `\n// Usage:\n`;
  scss += `// .button {\n`;
  scss += `//   background: $${scaleName}-60;\n`;
  scss += `// }\n`;

  return scss;
}

/**
 * Generate Less variables
 */
export function generateLess(
  scale: ColorScale,
  colors: ColorResult[],
  lightnessSteps: number[]
): string {
  const scaleName = scale.name.toLowerCase().replace(/\s/g, '-');
  let less = '';

  less += `// ${scale.name} Color Scale\n`;
  less += `// Generated by Lumat\n\n`;

  colors.forEach((c, i) => {
    const step = lightnessSteps[i];
    const actualL = Math.round(c.L * 100);

    less += `@${scaleName}-${step}: ${c.hex};`;
    if (actualL !== step) {
      less += ` // Actual L: ${actualL}`;
    }
    less += `\n`;
  });

  less += `\n// Usage:\n`;
  less += `// .button {\n`;
  less += `//   background: @${scaleName}-60;\n`;
  less += `// }\n`;

  return less;
}

/**
 * Generate PostCSS custom properties
 */
export function generatePostCSS(
  scale: ColorScale,
  colors: ColorResult[],
  lightnessSteps: number[]
): string {
  const scaleName = scale.name.toLowerCase().replace(/\s/g, '-');
  let postcss = '';

  postcss += `/* ${scale.name} Color Scale */\n`;
  postcss += `/* Generated by Lumat */\n\n`;

  postcss += `:root {\n`;
  colors.forEach((c, i) => {
    const step = lightnessSteps[i];
    postcss += `  --${scaleName}-${step}: ${c.hex};\n`;
  });
  postcss += `}\n`;

  return postcss;
}

/**
 * Get browser support information for export format
 */
export function getBrowserSupport(format: 'css' | 'p3' | 'oklch'): {
  chrome: string;
  firefox: string;
  safari: string;
  edge: string;
  support: number;
} {
  switch (format) {
    case 'css':
      return {
        chrome: '49+',
        firefox: '31+',
        safari: '9.1+',
        edge: '15+',
        support: 99
      };
    case 'p3':
      return {
        chrome: '111+',
        firefox: 'Not supported',
        safari: '10+',
        edge: '111+',
        support: 75
      };
    case 'oklch':
      return {
        chrome: '111+',
        firefox: '113+',
        safari: '15.4+',
        edge: '111+',
        support: 85
      };
  }
}
